import { IProduct } from './product.interface';
export class Product implements IProduct {
    id = 0;
    code = '';
    barcode = '';
    count = 0;
    price = 0;
    costPrice: number;
    originalPrice = 0;
    isSale = false;
    title = '';
    createdAt = '';
    modifiedAt = '';
    expiredAt = '';
    imageUrlsJson = '';
    avatarUrl = '';
    unit = '';
    foreignCurrency: string;
    costPriceForeign: number;
    onlineId = 0;
    isOption = false;
    isCombo = false;
    isPublic = false;
    isService = false;
    status = 0;
    itemsJson = '';
    items: any[] = [];
    materialsJson = '';
    materials: any[] = [];
    showOnWeb = true;
    isHotProduct = false;
    isNewProduct = false;
    showPriceOnWeb = false;
    isSelected = false;
    description: string;
    storeQuantity: number;
    units: any[] = null;
    unitsJson = '';
    fromUnit: string = null;
    staffId = 0;
    isMaterial = false;
    autoMaterials = false;
}
